services:
  - type: web
    name: memoryblitz-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: dpg-d054j1vgi27c73calun0-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: memoryblitz
      - key: DB_USER
        value: memoryblitz_user
      - key: DB_PASSWORD
        value: CRHFInu37nCMKGYa7ZIBXy0w6nNfKCnn
